--DROP TABLE S_DEPT;
--DROP TABLE S_EMP;

CREATE TABLE S_DEPT(
  DEPT_ID   NUMBER(7)     CONSTRAINT S_DEPT_ID_NN NOT NULL
, DEPT_NAME  VARCHAR2(25)  CONSTRAINT S_DEPT_NAME_NN NOT NULL
, CONSTRAINT S_DEPT_ID_PK PRIMARY KEY (DEPT_ID)
);

CREATE TABLE S_EMP(
  ID   NUMBER(7)     CONSTRAINT S_EMP_ID_NN NOT NULL
, NAME  VARCHAR2(25)  CONSTRAINT S_EMP_NAME_NN NOT NULL
, DEPT_ID   NUMBER(7)
, CONSTRAINT S_EMP_ID_PK PRIMARY KEY (ID)
);

ALTER TABLE S_EMP ADD CONSTRAINT S_DEPT_ID_FK
FOREIGN KEY (DEPT_ID) REFERENCES S_DEPT(DEPT_ID)
;
